version: '3'

services:

  nginx:
    build: .
    ports:
      - 8080:80
    container_name: pycontw-nginx
    restart: always
    hostname: pycontw-nginx
    volumes:
        - /var/www/letsencrypt:/var/www/letsencrypt

networks:
    default:
        external:
            name: pycontw-net

