name: Integration

on: push

jobs:
  integration:
    runs-on: ubuntu-18.04

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
        chmod +x ./hadolint
    - name: Linting
      run: |
        ./hadolint Dockerfile
        docker-compose -f docker-compose.yml config
        docker-compose build
